/*********************************************************/
/*																								*/
/*  FILE        :MiconRacer.cpp														*/
/*  DATE        :Mon, Oct 13, 2014													*/
/*  DESCRIPTION :Main program file.												*/
/*  CPU GROUP   :34C																*/
/*																								*/
/*  This file is generated by Renesas Project Generator (Ver.4.19).		*/
/*  NOTE:THIS IS A TYPICAL EXAMPLE.											*/
/**********************************************************/

#include "sfr_r834c.h"					/* Definition of the R8C/34C SFR */
#include "MiconRacer.h"

void main(void)
{
	asm("FCLR I");	/* Interrupt disabled */
	
	Hwsetup();
	InitInput();
	InitAdc();
	InitMotor(30);	//100%

	asm("FSET I");	/* Interrupt enable */

	bool runFlag = false ;
	//Loop of main
	while(1)	/* Main processing */
	{
		p0_7 = ~p0_7;

		if ( p0_7 == 0 ){
			//It is possible to monitor p0_1 and p0_3.
			p0_5 = ~p0_1;	//AN6 Sensor[2]
			p0_6 = ~p0_3;	//AN4 Sensor[0]
		}
		else {
			//It is possible to monitor p0_0 and p0_2.
			p0_5 = p0_0;	//AN7 Sensor[3]
			p0_6 = p0_2;	//AN5 Sensor[1]
		}
		Input();		//Digital input
		if ( runFlag == false )
		{
			if ( IsStartPB() == true )
			{
				InitFuzzy();
				MotorStart();
				runFlag = true ;
			}
		}
		else
		{
			if ( IsStartPB() == true )
			{
				MotorStop();
				runFlag = false ;
			}
			else
			{
				MotorControl();
			}
		}
	}
}
